
services:
    server:
        build:
            context: ./DockerWorld/
        image: gcc:latest
        volumes:
            - ./DockerWorld:/DockerWorld
        container_name: serv
        command: /bin/bash /DockerWorld/start.sh
        ports:
            -  8080:8080
        tty: true
    client:
        tty: true
        build:
            context: ./DockerSendLor/
        image: gcc:latest
        volumes:
            - ./DockerSendLor:/DockerClient
        container_name: cli
        command: /bin/bash /DockerClient/start.sh
        depends_on:
            - server
        network_mode: host